### ISSUE TITLE
`Error: Calling `brew cask install` is disabled! Use brew install [--cask] instead.`

### ISSUE THREAD

**Issue by justinTM** [maxyermayank/developer-mac-setup#1]
https://github.com/maxyermayank/developer-mac-setup/blob/c8fc4f5c6a445036c37977d3d9d32515263c6766/macSetup.sh#L54

**Comment by justinTM** [comment]
referenced in PR #2

**Comment by maxyermayank** [comment]
@justinTM  Appreciate you contributing back.
